# ansible/roles/postgres_master/handlers/main.yml
- name: Restart PostgreSQL
  become: true
  systemd:
    name: postgresql
    state: restarted
    enabled: true

- name: Reload PostgreSQL
  service:
    name: postgresql
    state: reloaded
