---
- name: Install Zabbix agent
  apt:
    name: zabbix-agent
    state: present
    update_cache: yes

- name: Configure Zabbix agent to connect to Zabbix server
  lineinfile:
    path: /etc/zabbix/zabbix_agentd.conf
    regexp: '^Server='
    line: 'Server=backup-zabbix'

- name: Restart agent
  service:
    name: zabbix-agent
    state: restarted
    enabled: true
