#roles/common/tasks/main.yml
---
- name: Install Zabbix agent
  apt:
    name: zabbix-agent
    state: present
    update_cache: yes

- name: Set Zabbix agent passive Server
  lineinfile:
    path: /etc/zabbix/zabbix_agentd.conf
    regexp: '^Server='
    line: "Server={{ zabbix_agent_server | default('backup-zabbix') }}"
  notify: Restart Zabbix agent

- name: Set Zabbix agent active ServerActive
  lineinfile:
    path: /etc/zabbix/zabbix_agentd.conf
    regexp: '^ServerActive='
    line: "ServerActive={{ zabbix_agent_server | default('backup-zabbix') }}"
  notify: Restart Zabbix agent

- name: Set Zabbix agent Hostname to inventory_hostname
  lineinfile:
    path: /etc/zabbix/zabbix_agentd.conf
    regexp: '^Hostname='
    line: "Hostname={{ inventory_hostname }}"
  notify: Restart Zabbix agent
